---
abstract: "Get a domain name's public suffix via the Mozilla Public Suffix List"
author:
  - 'Richard Simões <rsimoes AT cpan DOT org>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  HTTP::Tiny: 0
  IO::File: 0
  Module::Build: 0.3601
  Tie::File: 0
  URI: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.132830'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mozilla-PublicSuffix
requires:
  Exporter: 0
  URI: 0
  perl: 5.008
resources:
  bugtracker: https://github.com/rsimoes/mozilla-publicsuffix/issues
  homepage: https://metacpan.org/release/Mozilla-PublicSuffix
  repository: git://github.com/rsimoes/mozilla-publicsuffix.git
version: v0.1.19
